#probando el servidor

#GET http://localhost:8080/api/v1/home

#GET http://localhost:8080/api/v1/note
#POST http://localhost:8080/api/v1/note
#PUT http://localhost:8080/api/v1/note/1
#DELETE http://localhost:8080/api/v1/note/2